FROM cypress/included:9.6.0

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install python3.9 python3-pip -y

COPY test_requirements.txt /test_requirements.txt
RUN pip3 install -r test_requirements.txt
RUN rm test_requirements.txt

WORKDIR '/home/node_modules'
RUN npm i cypress-file-upload

WORKDIR /home
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]