version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    working_dir: /home/app
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/home/app/key.json
      - ./project:/home/app/project
      - ./tests:/home/app/tests
      - ./main.py:/home/app/main.py
      - ./mypy.ini:/home/app/mypy.ini
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/app/key.json
