FROM python:3.9-slim

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

WORKDIR /
COPY test_requirements.txt /test_requirements.txt
RUN pip3 install -r test_requirements.txt
RUN rm test_requirements.txt

WORKDIR /home
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]