FROM cypress/included:9.6.0

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install python3.9 python3-pip -y

COPY test_requirements.txt /test_requirements.txt
RUN pip3 install -r test_requirements.txt
RUN rm test_requirements.txt

COPY project home/project
COPY tests home/tests
COPY main.py home/main.py
COPY mypy.ini home/mypy.ini

WORKDIR /home