name: GitHub Actions

on: 
  push: 
    branches: 
      - master

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: make build
      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Start container
        run: make up
      - name: Run tests
        run: make test
      
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Run deploy
        uses: 'google-github-actions/deploy-appengine@v0'