name: GitHub Actions

on: push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.9'
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v3
      - name: Run static type check
        run: mypy mozaik.py
      - name: Run tests
        run: python -m pytest
      
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Run deploy
        uses: 'google-github-actions/deploy-appengine@v0'